<?php
//$arr= $this-$this>result;
//echo "<pre>";print_r($this->result);
$arr=array('haha','heh111e','hahahahahahahah');
$data=serialize($arr);
echo $data;
$data=unserialize($data);
print_r($data);
/* foreach ($this->result as $result)
        {
            echo $result->title . '<br />';
        }*/?>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-like" data-href="www.xminds.com" data-send="true" data-layout="standard" data-width="450" data-show-faces="true"></div>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-like-box" data-href="http://www.google.com" data-width="292" data-show-faces="true" data-stream="true" data-header="true"></div>





