<?php
phpinfo();
?>
<html>
    <head>
      <title>My Facebook Login Page</title>
    </head>
    <body>
      <div id="fb-root"></div>
      <script>
        window.fbAsyncInit = function() {
          FB.init({
            appId      : '339528116072903',
            status     : true,
            cookie     : true,
            xfbml      : true
          });
        };
        (function(d){
           var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
           js = d.createElement('script'); js.id = id; js.async = true;
           js.src = "//connect.facebook.net/en_US/all.js";
           d.getElementsByTagName('head')[0].appendChild(js);
         }(document));
      </script>
       <script>
      function gg() {
              FB.login(function(response) {
                 // alert(response.authResponse.accessToken);
                       if (response.authResponse) {
                         alert('Welcome!  Fetching your information.... ');
                         FB.api('/me', function(response) {
                           alert('Good to see you, ' + response.name + '.');
                           FB.logout(function(response) {
                             console.log('Logged out.');
                           });
                         });
                       } else {
                         alert('User cancelled login or did not fully authorize.');
                       }
                     }, {scope: 'email'});
      }
      </script>
      <div class="fb-login-button" onclick="gg();">Login with Facebook</div>
    </body>
 </html>